### ISSUE TITLE
Add dev/user modes.

### ISSUE THREAD

**Issue by RB-Lab** [NanoCraftGame/nanocraft#35]
User should not be able to:
1. Reset all tasks,
2. Reset everything,
3. See dormant tasks (those, which depend on unresolved decisions).

However, for developer these things are essential for debugging. 

I propose to:
1. Create a global variable `let mode: 'user' | 'developer' = 'user'`
2. Add two functions to the Window object: `setDevMode()` and `setUserMode()` which will
    a. Set that global variable to a proper value,
    b. Save the mode to localStorage, so that it wont be changed on each window reload.

**Comment by maxkhog** [comment]
!40
