### ISSUE TITLE
More than one full attention task can be inProgress

### ISSUE THREAD

**Issue by RB-Lab** [NanoCraftGame/nanocraft#36]
**Steps to reproduce**
1. Reset all tasks
2. Assign all available tasks to one person
3. Start simulation

**Expected result**
Only one task of type that has `attention: full` is `inProgress`, up to 4 `attention: partial` task can be in progress simultaneously, but only one that requires full attention here is [a quote from specification](https://github.com/NanoCraftGame/nanocraft/blob/main/src/lib/model/tasks.spec.md#task-statuses-and-transitions):

> - For each assignee at any given time only one _full attention_ task can be `inProgress`;
> - For each assignee at any given time no more than three _partial attention_ tasks can be
>  `inProgress` if that assignee has also a _full attention_ task assigned;
> - No more than five _partial attention_ tasks for an assignee can be `inProgress` simultaneously;

**Actual result**
Three full attention and two partial attention tasks are in progress simultaneously.

![Image](https://github.com/NanoCraftGame/nanocraft/assets/5694678/5fea3197-a34a-4644-b75f-99920146a582)

**Comment by maxkhog** [comment]
Is task completed?

**Comment by RB-Lab** [comment]
Apparently, yes. In #43 looks like it was referencing the wrong issue. 😃
