### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by RB-Lab** [NanoCraftGame/nanocraft#5]
Images we currently have are huge! 
We need to use [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) with srcsets instead, so that smaller devices won't waste traffic loading huge images for small screens.
Apparently Vite's image loader already [supports responsive images to an extend](https://kit.svelte.dev/docs/images), however, the problem is that in our case images [are loaded dynamically](https://github.com/NanoCraftGame/nanocraft/blob/main/src/lib/model/character.ts#L23-L41), so how to make these two approaches work together is an open question.

**Comment by Erball-M** [comment]
done in PR #39
